# This is a basic workflow to help you get started with Actions
name: word_games docker build
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}  
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      # Runs a single command using the runners shell
      - name: docker build 
        run: docker build -P -f word_games/Dockerfile.balena -t word_games/word_games:1.0.0


